import Navbar from "./Components/Navbar/Navbar";
import "./globals.css";
import styles from "./global.module.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import ReduxProvider from "./Redux/ReduxProvider";
import Provider from "./api/auth/[...nextauth]/Provider";

export const metadata = {
  title: "Server Components",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.outerContainer}>
        <Provider>
          <ReduxProvider>
            {/* <Navbar /> */}
            {children}
          </ReduxProvider>
        </Provider>
      </body>
    </html>
  );
}
